SELECT
    STEPID,
    MODULEID,
    PARAMETERID,
    PARAMETERNAME,
    PARAMETERVALUE,
    TARGETID,
    STEPORDER,
    JOBID,
    FREQUENCYID
FROM {{ params.DB }}.{{ params.JOBS_SCHEMA }}.{{ params.JOBS_TABLE }}
WHERE 1=1 LIMIT 1;
