name: Astronomer CI - DEV Auto Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'astronomer/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Decide deploy type
        id: decide
        env:
          CONFIG_PATH: astronomer/deployment_configs/dna-non-prod/dev/astro_deploy_config.yaml
        run: |
          set -euo pipefail

          # Determine a safe base commit for diffing this push
          BASE="${{ github.event.before }}"
          if [ -z "$BASE" ] || [ "$BASE" = "0000000000000000000000000000000000000000" ]; then
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              BASE="$(git rev-parse HEAD^)"
            else
              BASE="$(git rev-list --max-parents=0 HEAD)"
            fi
          fi

          # Rule 1: any change under astronomer/dags/ => dags-only
          if git diff --name-only "$BASE" "$GITHUB_SHA" | grep -q '^astronomer/dags/'; then
            DEPLOY_TYPE="dags-only"
          # Rule 2: if config changed, check whether only the 'dags:' list changed
          elif git diff --name-only "$BASE" "$GITHUB_SHA" | grep -q '^astronomer/deployment_configs/dna-non-prod/dev/astro_deploy_config.yaml$'; then
            head_list="$(awk '
              BEGIN{insec=0}
              /^dags:[[:space:]]*$/ {insec=1; next}
              insec==1 {
                if ($0 ~ /^[^[:space:]].*:[[:space:]]*$/) {insec=0; next}
                if ($0 ~ /^[[:space:]]*-/) { sub(/^[[:space:]]*-[[:space:]]*/, "", $0); sub(/\r$/, "", $0); print }
              }' "$CONFIG_PATH" | LC_ALL=C sort || true)"

            base_list="$(git show "$BASE:$CONFIG_PATH" 2>/dev/null | awk '
              BEGIN{insec=0}
              /^dags:[[:space:]]*$/ {insec=1; next}
              insec==1 {
                if ($0 ~ /^[^[:space:]].*:[[:space:]]*$/) {insec=0; next}
                if ($0 ~ /^[[:space:]]*-/) { sub(/^[[:space:]]*-[[:space:]]*/, "", $0); sub(/\r$/, "", $0); print }
              }' | LC_ALL=C sort || true)"

            if [ "$head_list" != "$base_list" ]; then
              DEPLOY_TYPE="dags-only"
            else
              DEPLOY_TYPE="image-and-dags"
            fi
          else
            DEPLOY_TYPE="image-and-dags"
          fi

          echo "DEPLOY_TYPE=$DEPLOY_TYPE" >> "$GITHUB_ENV"
          echo "Will deploy: $DEPLOY_TYPE"

      - name: Normalize line endings & make script executable
        working-directory: astronomer
        run: |
          sed -i 's/\r$//' build_astro_project.sh
          chmod +x build_astro_project.sh

      - name: Build astro_project (DEV)
        working-directory: astronomer
        run: ./build_astro_project.sh -e dev

      - name: Install Astro CLI
        run: curl -sSL install.astronomer.io | sudo bash -s -- v1.36.0


      - name: Deploy via Astro CLI (DEV)
        working-directory: astronomer/astro_project
        env:
          ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}
        run: |
          set -euo pipefail
          DEPLOY_ID="${{ vars.ASTRO_DEPLOYMENT_ID_DEV }}"
          if [ "${{ env.DEPLOY_TYPE }}" = "dags-only" ]; then
            astro deploy "$DEPLOY_ID" --dags --force
          else
            astro deploy "$DEPLOY_ID" --force
          fi
