name: Astronomer CI - Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "DEV | QA | UAT | PROD"
        required: true
      deploy_type:
        description: "dags-only or image-and-dags"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ inputs.env }}    # UPPERCASE for secrets/vars
      DEPLOY_TYPE: ${{ inputs.deploy_type }}
      ASTRO_API_TOKEN: ${{ secrets[format('ASTRO_API_TOKEN_{0}', inputs.env)] }}
      ASTRO_DEPLOYMENT_ID: ${{ vars[format('ASTRO_DEPLOYMENT_ID_{0}', inputs.env)] }}

    steps:
      - uses: actions/checkout@v4

      - name: Install jq + yq (python)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          python3 -m pip install --upgrade pip
          pip install yq

      - name: Build astro_project
        shell: bash
        run: |
          set -e
          # lowercase env for file paths
          ENV_LC=$(echo "$ENV" | tr '[:upper:]' '[:lower:]')

          if [[ "$ENV_LC" == "dev" || "$ENV_LC" == "qa" ]]; then ENV_GROUP="non-prod"; else ENV_GROUP="prod"; fi
          rm -rf astro_project && mkdir -p astro_project

          # dags
          DAGS_MANIFEST="dags/dags_environment/${ENV_GROUP}/dags_${ENV_LC}.yaml"
          mkdir -p astro_project/dags
          yq -r '.[]' "$DAGS_MANIFEST" | while IFS= read -r f; do cp "dags/$f" astro_project/dags/; done

          # include
          INCLUDE_MANIFEST="include/include_environment/${ENV_GROUP}/include_${ENV_LC}.yaml"
          mkdir -p astro_project/include
          yq -r '.[]' "$INCLUDE_MANIFEST" | while IFS= read -r pkg; do cp -r "include/$pkg" astro_project/include/; done

          # plugins
          PLUGINS_MANIFEST="plugins/plugins_environment/${ENV_GROUP}/plugins_${ENV_LC}.yaml"
          mkdir -p astro_project/plugins
          yq -r '.[]' "$PLUGINS_MANIFEST" | while IFS= read -r plg; do cp -r "plugins/$plg" astro_project/plugins/; done

          # dockerfile / packages / requirements (only for image_and_dags)
          if [[ "$DEPLOY_TYPE" == "image_and_dags" ]]; then
            cp "dockerfiles/${ENV_GROUP}/Dockerfile_${ENV_LC}"        astro_project/Dockerfile
            cp "packages/${ENV_GROUP}/packages_${ENV_LC}.txt"         astro_project/packages.txt
            cp "requirements/${ENV_GROUP}/requirements_${ENV_LC}.txt" astro_project/requirements.txt
          fi

          # .astro (always needed)
          if [ -d ".astro" ]; then cp -r .astro astro_project/.astro; else mkdir -p astro_project/.astro; fi

      - name: Show staged astro_project
        run: |
          echo "===== astro_project contents ====="
          find astro_project -maxdepth 3 -print | sort

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: ${{ env.ASTRO_DEPLOYMENT_ID }}
          root-folder: astro_project/
          deploy-type: ${{ env.DEPLOY_TYPE }}
          force: true
        env:
          ASTRO_API_TOKEN: ${{ env.ASTRO_API_TOKEN }}
