name: Astronomer CI - DEV Auto Deploy (Simple)

on:
  push:
    branches: [ main ]
    paths:
      - 'astronomer/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Decide deploy type
        id: decide
        env:
          CONFIG_PATH: astronomer/deployment_configs/dna-non-prod/dev/astro_deploy_config.yaml
        run: |
          set -euo pipefail

          # Figure out a safe base commit for the diff
          BASE="${{ github.event.before }}"
          if [[ -z "${BASE}" || "${BASE}" == "0000000000000000000000000000000000000000" ]]; then
            # first push on branch (or squash); fall back to previous commit if exists
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              BASE="$(git rev-parse HEAD^)"
            else
              BASE="$(git rev-list --max-parents=0 HEAD)"
            fi
          fi

          # 1) If any DAG file changed -> dags-only
          if git diff --name-only "$BASE" "$GITHUB_SHA" | grep -q '^astronomer/dags/'; then
            DEPLOY_TYPE="dags-only"
          else
            # 2) Otherwise, if config changed, diff only the 'dags:' list
            if git diff --name-only "$BASE" "$GITHUB_SHA" | grep -q '^astronomer/deployment_configs/dna-non-prod/dev/astro_deploy_config.yaml$'; then
              python -m pip install --upgrade pip >/dev/null
              python -m pip install PyYAML >/dev/null
              python - <<'PY' > /tmp/dep_type.txt
import os, sys, yaml, subprocess
cfg = os.environ["CONFIG_PATH"]

def load_rev(path, rev=None):
    if rev:
        try:
            txt = subprocess.check_output(["git","show", f"{rev}:{path}"], text=True)
            return yaml.safe_load(txt) or {}
        except subprocess.CalledProcessError:
            return {}
    else:
        with open(path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}

base = os.environ.get("BASE")
head_cfg = load_rev(cfg, None)
base_cfg = load_rev(cfg, base) if base else {}
dags_changed = (head_cfg.get("dags") or []) != (base_cfg.get("dags") or [])
print("dags-only" if dags_changed else "image-and-dags")
PY
              DEPLOY_TYPE="$(cat /tmp/dep_type.txt)"
            else
              DEPLOY_TYPE="image-and-dags"
            fi
          fi

          echo "DEPLOY_TYPE=$DEPLOY_TYPE" >> "$GITHUB_ENV"
          echo "Will deploy: $DEPLOY_TYPE"

      - name: Normalize line endings & make script executable
        working-directory: astronomer
        run: |
          sed -i 's/\r$//' build_astro_project.sh
          chmod +x build_astro_project.sh

      - name: Build astro_project (DEV)
        working-directory: astronomer
        run: ./build_astro_project.sh -e dev

      - name: Deploy to Astro (DEV)
        uses: astronomer/deploy-action@v0.10.1
        with:
          deployment-id: ${{ vars.ASTRO_DEPLOYMENT_ID_DEV }}
          root-folder: astronomer/astro_project/
          deploy-type: ${{ env.DEPLOY_TYPE }}
          force: true
        env:
          ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}
