name: Astronomer CI - DEV Manual Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        description: "dags-only | image-and-dags"
        type: choice
        required: true
        options: [dags-only, image-and-dags]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable (normalize line endings)
        working-directory: astronomer
        run: |
          sed -i 's/\r$//' build_astro_project.sh
          chmod +x build_astro_project.sh

      - name: Build astro_project (DEV)
        working-directory: astronomer
        run: ./build_astro_project.sh -e dev

      - name: Deploy via Astro CLI (DEV)
        working-directory: astronomer/astro_project
        env:
          ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}
        run: |
          set -euo pipefail
          DEPLOY_ID="${{ vars.ASTRO_DEPLOYMENT_ID_DEV }}"
          if [ "${{ env.DEPLOY_TYPE }}" = "dags-only" ]; then
            astro deploy "$DEPLOY_ID" --dags --force
          else
            astro deploy "$DEPLOY_ID" --force
          fi
